### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by CamilaTokisaki** [Dorijan-Cirkveni/TMIWNHANDANHHTHTYVM#2]
Hello, you have not indicated anywhere about the method of communication with you, so I am writing here, I would like to talk to you, since we (my group of translators) want to get permission to translate your mod into Russian, if you are interested in my suggestion, please write to me in discord

CamilaTokisaki#5351

**Comment by Dorijan-Cirkveni** [comment]
Sorry, forgot to put a communication method here. Also didn't know this part of github existed
